"""Frozen measured-container-v1 Docker creation and tmpfs layout.

Existing receipts select this implementation through their toolchain profile.
Do not edit this file after pinning its digest: add a v2 module and profile.
"""
import json

from docker.types import LogConfig,Ulimit


def phase_tmpfs_v1(language, phase, limits, *, layout):
    if layout not in ('work-v1','bpp-split-v1'):
        raise ValueError('Unknown trusted scratch layout')
    mounts = {'/control': f'rw,noexec,nosuid,nodev,size={limits.output_bytes+65536},mode=0700'}
    work_bytes = limits.tmp_bytes
    if layout == 'bpp-split-v1' and phase == 'compile':
        # The installed B++ launcher creates /tmp/bpp_run_* even with TMPDIR.
        # Split, never duplicate, the frozen scratch budget. Run phases keep
        # /tmp read-only. The changed layout has a distinct toolchain version.
        if work_bytes < 8192 or work_bytes % 4096:
            raise ValueError('B++ compile scratch must contain aligned 4 KiB pages')
        private_tmp_bytes = (work_bytes // 8192) * 4096
        work_bytes -= private_tmp_bytes
        mounts['/tmp'] = f'rw,exec,nosuid,nodev,size={private_tmp_bytes},mode=1777'
    if work_bytes:
        mounts['/work'] = f'rw,exec,nosuid,nodev,size={work_bytes},mode=1777'
    return mounts


def phase_create_options_v1(*, phase_id, phase, limits, argv, language,
        layout, inputs, source, artifact, empty, image_digest,
        launcher_script, labels):
    """Return only the original v1 create options; no caller-supplied extras."""
    volumes={str(inputs):{'bind':'/input','mode':'ro'}}
    volumes[str(source if phase=='compile' else artifact)]={
        'bind':'/source' if phase=='compile' else '/artifact','mode':'ro'}
    tmpfs=phase_tmpfs_v1(language,phase,limits,layout=layout)
    if not limits.tmp_bytes:
        volumes[str(empty)]={'bind':'/work','mode':'ro'}
    spec=dict(version=1,phase=phase,argv=argv,stdin='/input/stdin',
        limits=limits.model_dump(by_alias=True))
    return dict(
        image=image_digest,entrypoint=['/usr/bin/python3','-I','-c'],
        command=[launcher_script],detach=True,
        name='compiler-measured-'+phase_id,
        labels={**labels,'webcompiler.phase':phase_id},
        user='0:0',network_disabled=True,read_only=True,
        tmpfs=tmpfs,volumes=volumes,
        # Docker's default writable /dev/shm would be unaccounted scratch.
        init=False,cgroupns='private',ipc_mode='none',
        healthcheck={'test':['NONE']},
        mem_limit=limits.memory_bytes,memswap_limit=limits.memory_bytes,
        nano_cpus=1000000000,pids_limit=limits.pids,
        ulimits=[Ulimit(name='nofile',soft=64,hard=64)],
        cap_drop=['ALL'],cap_add=['KILL','SETUID','SETGID'],
        security_opt=['no-new-privileges'],
        log_config=LogConfig(type='none'),
        environment={'JUDGE_PHASE_SPEC':json.dumps(spec,separators=(',',':'))},
    )
