import type { ASTGraph, ASTNode, SourceRange } from './compilerApi';

export type MappingKind = 'expression' | 'statement' | 'scope' | 'range' | 'approximate' | 'generated' | 'unavailable';

export interface MappingQuality {
  kind: MappingKind;
  label: string;
  description: string;
}

export interface MappingQualityInput {
  ranges?: SourceRange[];
  generated?: boolean;
  generatedReason?: string;
  ast?: ASTGraph;
  approximate?: boolean;
}

const expressionTypes = new Set([
  'literal', 'float', 'string', 'ident', 'identifier', 'binary', 'binaryexpression', 'unary', 'unaryexpression',
  'call', 'callexpr', 'callexpression', 'genericcall', 'staticgenericcall', 'methodcall', 'safemethodcall', 'callptr',
  'addrof', 'deref', 'deref8', 'cast', 'memberaccess', 'safememberaccess', 'structliteral',
  'genericstructliteral', 'sizeof', 'sizeofexpr', 'index', 'safeindex', 'slice', 'try', 'super', 'ternary',
  'new', 'stackctor',
]);

const statementTypes = new Set([
  'return', 'returnstmt', 'vardecl', 'variabledeclaration', 'constdecl', 'constdeclaration', 'assign', 'assignment',
  'exprstmt', 'expressionstatement', 'if', 'ifstatement', 'while', 'whilestatement', 'for', 'forstatement',
  'dowhile', 'dowhilestatement', 'matchcompat', 'match', 'case', 'break', 'continue', 'asm', 'alias', 'defer',
  'delete', 'trystmt', 'trystatement', 'throwstmt', 'throwstatement',
]);

const scopeTypes = new Set([
  'program', 'block', 'function', 'func', 'functiondeclaration', 'functiondecl',
]);

function normalizedType(type: string): string {
  return type.trim().toLowerCase().replace(/[\s_-]/g, '');
}

function kindForNodeType(type: string): Extract<MappingKind, 'expression' | 'statement' | 'scope'> | undefined {
  const normalized = normalizedType(type);
  if (expressionTypes.has(normalized)) {
    return 'expression';
  }
  if (statementTypes.has(normalized)) {
    return 'statement';
  }
  if (scopeTypes.has(normalized)) {
    return 'scope';
  }
  return undefined;
}

function rangeReferences(range: SourceRange): string[] {
  return [range.astNodeId, range.originNodeId].filter((id): id is string => typeof id === 'string');
}

function nodeReferences(node: ASTNode): string[] {
  const metadata = node.metadata ?? {};
  return [node.id, metadata.astNodeId, metadata.originNodeId].filter((id): id is string => typeof id === 'string');
}

// One immutable compilation snapshot is shared by thousands of output rows.
// Index its identifiers once instead of scanning the whole AST per badge.
const referenceIndexes = new WeakMap<ASTGraph, Map<string, ASTNode[]>>();

function matchingNodes(range: SourceRange, ast: ASTGraph | undefined): ASTNode[] {
  if (!ast) {
    return [];
  }

  let index = referenceIndexes.get(ast);
  if (!index) {
    index = new Map();
    ast.nodes.forEach(node => new Set(nodeReferences(node)).forEach(id => {
      const matches = index!.get(id) ?? [];
      matches.push(node);
      index!.set(id, matches);
    }));
    referenceIndexes.set(ast, index);
  }
  return [...new Set(rangeReferences(range).flatMap(id => index.get(id) ?? []))];
}

function describe(kind: MappingKind, generated: boolean, generatedReason: string | undefined): MappingQuality {
  const generatedNote = generated
    ? ` Generated${generatedReason ? `: ${generatedReason}.` : ' by the compiler.'}`
    : '';

  switch (kind) {
    case 'expression':
      return { kind, label: 'Expression', description: `Maps directly to one AST expression.${generatedNote}` };
    case 'statement':
      return { kind, label: 'Statement', description: `Maps directly to one AST statement.${generatedNote}` };
    case 'scope':
      return { kind, label: 'Scope', description: `Maps directly to one AST scope.${generatedNote}` };
    case 'range':
      return { kind, label: 'Source range', description: `Has source-range metadata but no single AST classification.${generatedNote}` };
    case 'approximate':
      return { kind, label: 'Approximate source range', description: 'Uses an approximate legacy source mapping.' };
    case 'generated':
      return {
        kind,
        label: 'Generated code',
        description: `Generated by the compiler${generatedReason ? `: ${generatedReason}` : ''}; no source range is available.`,
      };
    case 'unavailable':
      return { kind, label: 'Source unavailable', description: 'No source-range mapping is available.' };
  }
}

/**
 * Rates a mapping using only source-range identifiers and AST type evidence.
 * A generated marker augments an existing range mapping; it does not erase it.
 */
export function classifyMapping(input: MappingQualityInput): MappingQuality {
  const ranges = input.ranges ?? [];
  const hasRanges = ranges.length > 0;

  if (input.approximate && hasRanges) {
    return describe('approximate', input.generated === true, input.generatedReason);
  }

  if (!hasRanges) {
    return input.generated === true
      ? describe('generated', true, input.generatedReason)
      : describe('unavailable', false, undefined);
  }

  // Several range records may refer to different source constructs. Preserve
  // that uncertainty rather than choosing a type from their rendered extent.
  if (ranges.length !== 1) {
    return describe('range', input.generated === true, input.generatedReason);
  }

  const matches = matchingNodes(ranges[0], input.ast);
  if (matches.length !== 1) return describe('range', input.generated === true, input.generatedReason);
  const types = new Set(matches.map((node) => kindForNodeType(node.type)));
  if (types.has(undefined)) return describe('range', input.generated === true, input.generatedReason);
  if (types.size !== 1) {
    return describe('range', input.generated === true, input.generatedReason);
  }

  const [kind] = types;
  if (!kind) {
    return describe('range', input.generated === true, input.generatedReason);
  }
  return describe(kind, input.generated === true, input.generatedReason);
}
