import { describe, expect, it } from 'vitest';
import type { ASTGraph, ASTNode, SourceRange } from './compilerApi';
import { classifyMapping } from './mappingQuality';

const range = (references: Pick<SourceRange, 'astNodeId' | 'originNodeId'> = {}): SourceRange => ({
  startLine: 1,
  startColumn: 1,
  endLine: 1,
  endColumn: 2,
  ...references,
});

const node = (id: string, type: string, metadata?: ASTNode['metadata']): ASTNode => ({
  id,
  type,
  label: id,
  children: [],
  metadata,
});

const ast = (...nodes: ASTNode[]): ASTGraph => ({ nodes, edges: [] });

describe('classifyMapping', () => {
  it('classifies direct AST matches after normalizing compiler type spelling', () => {
    expect(classifyMapping({ ranges: [range({ astNodeId: 'ident' })], ast: ast(node('ident', 'Ident')) }).kind).toBe('expression');
    expect(classifyMapping({ ranges: [range({ astNodeId: 'decl' })], ast: ast(node('decl', 'var_decl')) }).kind).toBe('statement');
    expect(classifyMapping({ ranges: [range({ astNodeId: 'fn' })], ast: ast(node('fn', 'FUNCTION-DECLARATION')) }).kind).toBe('scope');
  });

  it('matches source identifiers against AST metadata as well as node ids', () => {
    const result = classifyMapping({
      ranges: [range({ originNodeId: 'original-call' })],
      ast: ast(node('lowered-call', 'Call', { originNodeId: 'original-call' })),
    });

    expect(result.kind).toBe('expression');
  });

  it('does not infer an AST class from a range extent or an unmatched AST label', () => {
    const broadRange = {
      ...range({ astNodeId: 'missing' }),
      startLine: 1,
      endLine: 200,
      endColumn: 1,
    };
    const result = classifyMapping({ ranges: [broadRange], ast: ast(node('different', 'Ident')) });

    expect(result.kind).toBe('range');
  });

  it('uses range for multiple mappings or a direct type conflict', () => {
    expect(classifyMapping({
      ranges: [range({ astNodeId: 'one' }), range({ astNodeId: 'two' })],
      ast: ast(node('one', 'Literal'), node('two', 'Return')),
    }).kind).toBe('range');
    expect(classifyMapping({
      ranges: [range({ astNodeId: 'shared' })],
      ast: ast(node('shared', 'Literal'), node('lowered', 'Return', { astNodeId: 'shared' })),
    }).kind).toBe('range');
  });

  it('gives an approximate range priority only when a range exists', () => {
    expect(classifyMapping({
      approximate: true,
      ranges: [range({ astNodeId: 'ident' })],
      ast: ast(node('ident', 'Ident')),
    }).kind).toBe('approximate');
    expect(classifyMapping({ approximate: true }).kind).toBe('unavailable');
  });

  it('keeps a generated node connected when it has a source range', () => {
    const connected = classifyMapping({
      generated: true,
      generatedReason: 'lowering',
      ranges: [range({ astNodeId: 'return' })],
      ast: ast(node('return', 'Return')),
    });

    expect(connected).toMatchObject({ kind: 'statement', label: 'Statement' });
    expect(connected.description).toContain('Generated: lowering.');
    expect(classifyMapping({ generated: true, generatedReason: 'synthetic block' })).toEqual({
      kind: 'generated',
      label: 'Generated code',
      description: 'Generated by the compiler: synthetic block; no source range is available.',
    });
  });

  it('reports unavailable when no source or generated evidence exists', () => {
    expect(classifyMapping({})).toEqual({
      kind: 'unavailable',
      label: 'Source unavailable',
      description: 'No source-range mapping is available.',
    });
  });

  it('does not label an unknown conflicting AST type as an exact expression', () => {
    expect(classifyMapping({ ranges: [range({ astNodeId: 'shared' })], ast: ast(node('shared', 'Literal'), node('unknown', 'FutureNode', { originNodeId: 'shared' })) }).kind).toBe('range');
  });

  it('does not call multiple AST candidates a single exact expression', () => {
    expect(classifyMapping({ ranges: [range({ astNodeId: 'shared' })], ast: ast(node('shared', 'Literal'), node('second', 'Literal', { originNodeId: 'shared' })) }).kind).toBe('range');
  });
});
